version: "3.5"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-gemini-chatbot
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - ./node_modules
    environment:
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="${NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY}"
      - CLERK_SECRET_KEY="${CLERK_SECRET_KEY}"
      - NEXT_PUBLIC_GOOGLE_API_KEY="${NEXT_PUBLIC_GOOGLE_API_KEY}"
